{% set name = "pmtiles" %}
{% set version = "3.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pmtiles-{{ version }}.tar.gz
  sha256: 0f594a61b37fca039f06162428781f76a4233f5beea94444702f0dc41f20f007

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pmtiles
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/protomaps/pmtiles
  summary: Library and utilities to write and read PMTiles archives - cloud-optimized archives of map tiles.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
