{% set name = "pmtiles" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pmtiles-{{ version }}.tar.gz
  sha256: 02871f649e81d408d6149824402d310ddfefe6b9bdf646d6784ef3221b36286f

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pmtiles
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/protomaps/pmtiles
  summary: Library and utilities to write and read PMTiles archives - cloud-optimized archives of map tiles.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
