{% set name = "pmtiles" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pmtiles-{{ version }}.tar.gz
  sha256: 4a141eda371677961266fab435ff880e24d83a14fdd427f3a24606743288e459

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - pmtiles
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/protomaps/pmtiles
  summary: Library and utilities to write and read PMTiles archives - cloud-optimized archives of map tiles.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
